### ISSUE TITLE
If using profile path for batch file, sshdump.exe not found

### ISSUE THREAD

**Issue by patoberli** [wifinigel/wlan-extcap-win#4]
Hi
Small bug report in regards to the wlanpidump.bat file. 
When using the new profile directory for this file %appdata%\Wireshark\extcap (extcap directory must be created first) on Windows, the batch file will not find the sshdump.exe in the directory C:\Program Files\Wireshark\extcap\. 
One way is to change the path in the batch file to (line 116):
	set "sshdump_path=C:\Program Files\Wireshark\extcap\sshdump.exe"
Or to copy the sshdump.exe to the %appdata%\Wireshark\extcap\ directory. 
I think an adjustment to the README would be the easiest solution.
Regards
Patrick

**Comment by cpajr** [comment]
I can confirm this bug as well on the wlanpidump_v2.bat file as well.

**Comment by wifinigel** [comment]
Thanks for the heads-up, I'll get this fixed.

**Comment by wifinigel** [comment]
Updated ReadMe.
